(library
 (name proof_conversion_pairing_utils)
 (libraries core_kernel bignum.bigint)
 (foreign_archives pairing_utils)
 (no_dynlink)
 (c_library_flags :standard -lpthread -Wl,--allow-multiple-definition)
 (instrumentation
  (backend bisect_ppx))
 (preprocess
  (pps ppx_version ppx_jane)))

; Build the Rust pairing-utils static library.
(rule
 (targets libpairing_utils.a)
 (deps
  (source_tree rust)
  (env_var PAIRING_UTILS_STATIC_LIB))
 (locks /cargo-lock)
 (action
  (no-infer
   (bash
    "SRCDIR=\"$(git -C %{workspace_root} rev-parse --show-toplevel)/src/lib/proof_conversion_pairing_utils/rust\"; TGTDIR=\"$(git -C %{workspace_root} rev-parse --show-toplevel)/_build/cargo_pairing_utils\"; if [ -n \"${PAIRING_UTILS_STATIC_LIB:-}\" ]; then cp \"$PAIRING_UTILS_STATIC_LIB\" %{targets}; else cargo build -p pairing-utils --release --manifest-path \"$SRCDIR/Cargo.toml\" --target-dir \"$TGTDIR\" && cp \"$TGTDIR/release/libpairing_utils.a\" %{targets}; fi"))))
