(include_subdirs unqualified)

(library
 (name proof_conversion)
 (libraries
  core_kernel
  pickles
  pickles_types
  kimchi_pasta
  kimchi_pasta.basic
  mina_base
  promise
  snarky.backendless
  kimchi_backend_common
  kimchi_backend.gadgets
  yojson
  bignum.bigint
  snarky_foreign_field
  random_oracle
  digestif.ocaml
  proof_conversion_pairing_utils
  proof_conversion_circuit_kit
  proof_conversion_bn254
  proof_conversion_compressor
  proof_conversion_groth16
  proof_conversion_pairing_utils_bridge)
 (instrumentation
  (backend bisect_ppx))
 (preprocess
  (pps ppx_version ppx_jane)))
