(include_subdirs no)

(executable
 (name test_pickles_compat)
 (modules test_pickles_compat)
 (libraries
  core_kernel
  pickles
  pickles_types
  kimchi_pasta
  kimchi_pasta.basic
  mina_base
  promise
  snarky.backendless)
 (instrumentation
  (backend bisect_ppx))
 (preprocess
  (pps ppx_version ppx_jane)))

(executable
 (name test_tower_field)
 (modules test_tower_field)
 (libraries
  core_kernel
  proof_conversion
  snarky_foreign_field
  bignum.bigint)
 (instrumentation
  (backend bisect_ppx))
 (preprocess
  (pps ppx_version ppx_jane)))

(executable
 (name test_groth16_vk)
 (modules test_groth16_vk)
 (libraries
  core_kernel
  pickles
  pickles_types
  kimchi_pasta
  mina_base
  promise
  proof_conversion)
 (instrumentation
  (backend bisect_ppx))
 (preprocess
  (pps ppx_version ppx_jane)))

(executable
 (name test_groth16_ghash)
 (modules test_groth16_ghash)
 (libraries
  core_kernel
  pickles
  pickles_types
  kimchi_pasta
  mina_base
  promise
  proof_conversion
  random_oracle)
 (instrumentation
  (backend bisect_ppx))
 (preprocess
  (pps ppx_version ppx_jane)))

(executable
 (name test_groth16_cinv)
 (modules test_groth16_cinv)
 (libraries
  core_kernel
  pickles
  pickles_types
  kimchi_pasta
  mina_base
  promise
  proof_conversion)
 (instrumentation
  (backend bisect_ppx))
 (preprocess
  (pps ppx_version ppx_jane)))

(executable
 (name test_plonk_e2e)
 (modules test_plonk_e2e)
 (libraries
  core_kernel
  pickles
  pickles_types
  kimchi_pasta
  mina_base
  promise
  proof_conversion)
 (instrumentation
  (backend bisect_ppx))
 (preprocess
  (pps ppx_version ppx_jane)))

(executable
 (name test_gate_comparison)
 (modules test_gate_comparison gate_comparison)
 (libraries
  core_kernel
  yojson)
 (instrumentation
  (backend bisect_ppx))
 (preprocess
  (pps ppx_version ppx_jane)))
