(** Test that Pickles circuits compiled with [o1js_compatible_mode] produce
    verification keys matching the equivalent o1js ZkProgram.

    Usage:
      dune exec src/lib/proof_conversion/test/test_pickles_compat.exe

    On VK mismatch, set DUMP_GATES=<path> to write the full step circuit
    gate JSON to the given file for comparison against the o1js equivalent.

    Reference VK hashes are generated by:
      src/lib/proof_conversion/test/generate_pickles_compat_fixture.ts *)

open Core_kernel

module Step = Pickles.Impls.Step

(** {2 Simple program: publicInput.assertEquals(x * x)} *)

(** Replicates the [dummy_constraints] function from o1js's pickles_bindings.ml.
    o1js injects these into every ZkProgram method to ensure the circuit always
    contains at least one instance of each EC gate type (EndoMulScalar,
    VarBaseMul, EndoMul, CompleteAdd), which is required by the Kimchi prover. *)
let dummy_constraints () =
  let open Step in
  let module Inner_curve = Pickles.Step_main_inputs.Inner_curve in
  let module Ops = Pickles.Step_main_inputs.Ops in
  let inner_curve_typ : (Field.t * Field.t, Kimchi_pasta.Pasta.Pallas.t) Typ.t =
    Typ.transport Inner_curve.typ
      ~there:Kimchi_pasta.Pasta.Pallas.to_affine_exn
      ~back:Kimchi_pasta.Pasta.Pallas.of_affine
  in
  let x = exists Field.typ ~compute:(fun () -> Field.Constant.of_int 3) in
  let g = exists inner_curve_typ ~compute:(fun _ -> Kimchi_pasta.Pasta.Pallas.one) in
  ignore
    ( Pickles.Scalar_challenge.to_field_checked'
        (module Step)
        ~num_bits:16
        (Kimchi_backend_common.Scalar_challenge.create x)
      : Field.t * Field.t * Field.t ) ;
  ignore
    ( Ops.scale_fast g ~num_bits:5
        (Pickles_types.Shifted_value.Type1.Shifted_value x)
      : Inner_curve.t ) ;
  ignore
    ( Pickles.Step_verifier.Scalar_challenge.endo g ~num_bits:4
        (Kimchi_backend_common.Scalar_challenge.create x)
      : Field.t * Field.t )

module Simple = struct
  let rule : _ Pickles.Inductive_rule.Promise.t =
    { identifier = "base"
    ; prevs = []
    ; main =
        (fun { public_input = pub } ->
          let open Step in
          dummy_constraints () ;
          let pub_field = pub.(0) in
          let x =
            exists Field.typ ~compute:(fun () -> Field.Constant.zero)
          in
          let x_sq = Field.mul x x in
          Field.Assert.equal pub_field x_sq ;
          Promise.return
            { Pickles.Inductive_rule.previous_proof_statements = []
            ; public_output = [||]
            ; auxiliary_output = ()
            } )
    ; feature_flags = Pickles_types.Plonk_types.Features.none_bool
    }
end

(** Match o1js's [public_input_typ] which uses [Typ.array ~length:n Field.typ] *)
let public_input_typ n = Step.Typ.array ~length:n Step.Field.typ

let compile_and_get_vk ~name ~choices =
  let tag, _cache, (module Proof), _provers =
    Pickles.compile_promise
      ~public_input:
        (Pickles.Inductive_rule.Input_and_output
           (public_input_typ 1, public_input_typ 0) )
      ~auxiliary_typ:Step.Typ.unit
      ~max_proofs_verified:(module Pickles_types.Nat.N0)
      ~name
      ~o1js_compatible_mode:true
      ~choices
      ()
  in
  (* Get the VK via the Side_loaded path, same as o1js *)
  let vk_promise =
    Pickles.Side_loaded.Verification_key.of_compiled_promise tag
  in
  let vk = Promise.block_on_async_exn (fun () -> vk_promise) in
  let hash = Mina_base.Zkapp_account.digest_vk vk in
  let data = Pickles.Side_loaded.Verification_key.to_base64 vk in
  ignore (Proof.verification_key_promise : Pickles.Verification_key.t Promise.t Lazy.t) ;
  (hash, data)

let () =
  (* Expected VK hashes from o1js fixture *)
  let expected_simple_vk_hash =
    "7366579521807958688380708523943536275961244156544953379731585537782625645675"
  in
  let dump_gates_path = Stdlib.Sys.getenv_opt "DUMP_GATES" in
  let all_pass = ref true in

  printf "Pickles o1js compatibility test\n" ;
  printf "================================\n" ;

  (* --- Simple program --- *)
  printf "\n[simple-compat-test]\n" ;
  printf "  Compiling... %!" ;
  let hash, data =
    compile_and_get_vk ~name:"simple-compat-test"
      ~choices:(fun ~self:_ -> [ Simple.rule ])
  in
  let hash_str =
    Kimchi_pasta.Pasta.Fp.to_string hash
  in
  printf "done\n" ;
  printf "  VK hash (OCaml):  %s\n" hash_str ;
  printf "  VK hash (o1js):   %s\n" expected_simple_vk_hash ;
  if String.equal hash_str expected_simple_vk_hash then
    printf "  PASS\n"
  else (
    printf "  FAIL - VK hashes differ\n" ;
    all_pass := false ;
    (* Dump VK data for manual comparison *)
    ( match dump_gates_path with
    | Some path ->
        let oc = Out_channel.create path in
        Out_channel.output_string oc data ;
        Out_channel.close oc ;
        printf "  Wrote OCaml VK data to %s\n" path ;
        printf "  Compare with o1js VK data to find divergence.\n"
    | None ->
        printf "  (set DUMP_GATES=<path> to write OCaml VK data for comparison)\n" ) ) ;

  if not !all_pass then (
    printf "\nFAILED\n" ;
    exit 1 )
  else printf "\nAll compatibility checks passed.\n"
