(** Test that Pickles circuits compiled with [o1js_compatible_mode] produce
    verification keys matching the equivalent o1js ZkProgram.

    Usage:
      dune exec src/lib/proof_conversion/test/test_pickles_compat.exe

    Reference VK hashes are generated by:
      src/lib/proof_conversion/test/generate_pickles_compat_fixture.ts *)

open Core_kernel
module Step = Pickles.Impls.Step

(** Replicates the [dummy_constraints] function from o1js's pickles_bindings.ml.
    o1js injects these into every ZkProgram method to ensure the circuit always
    contains at least one instance of each EC gate type (EndoMulScalar,
    VarBaseMul, EndoMul, CompleteAdd), which is required by the Kimchi prover. *)
let dummy_constraints () =
  let open Step in
  let module Inner_curve = Pickles.Step_main_inputs.Inner_curve in
  let module Ops = Pickles.Step_main_inputs.Ops in
  let inner_curve_typ : (Field.t * Field.t, Kimchi_pasta.Pasta.Pallas.t) Typ.t =
    Typ.transport Inner_curve.typ ~there:Kimchi_pasta.Pasta.Pallas.to_affine_exn
      ~back:Kimchi_pasta.Pasta.Pallas.of_affine
  in
  let x = exists Field.typ ~compute:(fun () -> Field.Constant.of_int 3) in
  let g =
    exists inner_curve_typ ~compute:(fun _ -> Kimchi_pasta.Pasta.Pallas.one)
  in
  ignore
    ( Pickles.Scalar_challenge.to_field_checked'
        (module Step)
        ~num_bits:16
        (Kimchi_backend_common.Scalar_challenge.create x)
      : Field.t * Field.t * Field.t ) ;
  ignore
    ( Ops.scale_fast g ~num_bits:5
        (Pickles_types.Shifted_value.Type1.Shifted_value x)
      : Inner_curve.t ) ;
  ignore
    ( Pickles.Step_verifier.Scalar_challenge.endo g ~num_bits:4
        (Kimchi_backend_common.Scalar_challenge.create x)
      : Field.t * Field.t )

(** Match o1js's [public_input_typ] which uses [Typ.array ~length:n Field.typ] *)
let public_input_typ n = Step.Typ.array ~length:n Step.Field.typ


(* ------------------------------------------------------------------ *)
(* Test 1: Non-recursive program (max_proofs_verified = N0)            *)
(* ------------------------------------------------------------------ *)

module Simple = struct
  let rule : _ Pickles.Inductive_rule.Promise.t =
    { identifier = "base"
    ; prevs = []
    ; main =
        (fun { public_input = pub } ->
          let open Step in
          dummy_constraints () ;
          let pub_field = pub.(0) in
          let x = exists Field.typ ~compute:(fun () -> Field.Constant.zero) in
          let x_sq = Field.mul x x in
          Field.Assert.equal pub_field x_sq ;
          Promise.return
            { Pickles.Inductive_rule.previous_proof_statements = []
            ; public_output = [||]
            ; auxiliary_output = ()
            } )
    ; feature_flags = Pickles_types.Plonk_types.Features.none_bool
    }
end

let compile_simple ~name =
  let tag, _cache, (module Proof), _provers =
    Pickles.compile_promise
      ~public_input:
        (Pickles.Inductive_rule.Input_and_output
           (public_input_typ 1, public_input_typ 0) )
      ~auxiliary_typ:Step.Typ.unit
      ~max_proofs_verified:(module Pickles_types.Nat.N0)
      ~name ~o1js_compatible_mode:false
      ~choices:(fun ~self:_ -> [ Simple.rule ])
      ()
  in
  let vk_promise =
    Pickles.Side_loaded.Verification_key.of_compiled_promise tag
  in
  let vk = Promise.block_on_async_exn (fun () -> vk_promise) in
  let hash = Mina_base.Zkapp_account.digest_vk vk in
  ignore
    ( Proof.verification_key_promise
      : Pickles.Verification_key.t Promise.t Lazy.t ) ;
  hash

(* ------------------------------------------------------------------ *)
(* Test 2: Recursive program (max_proofs_verified = N1)                *)
(*   base: publicInput.assertEquals(0)                                 *)
(*   recursive: prev.verify(); publicInput.assertEquals(prev + 1)      *)
(* ------------------------------------------------------------------ *)

module Recursive = struct
  let base_rule : _ Pickles.Inductive_rule.Promise.t =
    { identifier = "base"
    ; prevs = []
    ; main =
        (fun { public_input = pub } ->
          let open Step in
          dummy_constraints () ;
          let pub_field = pub.(0) in
          Field.Assert.equal pub_field (Field.of_int 0) ;
          Promise.return
            { Pickles.Inductive_rule.previous_proof_statements = []
            ; public_output = [||]
            ; auxiliary_output = ()
            } )
    ; feature_flags = Pickles_types.Plonk_types.Features.none_bool
    }

  (** The recursive rule. [prevs = [self]] tells Pickles to verify one
      previous proof of the same type. The framework handles witnessing
      the proof and feeding it to the step verifier. *)
  let recursive_rule self : _ Pickles.Inductive_rule.Promise.t =
    { identifier = "recursive"
    ; prevs = [ self ]
    ; main =
        (fun { public_input = pub } ->
          let open Step in
          dummy_constraints () ;
          let pub_field = pub.(0) in
          (* Witness the previous statement (input, output) pair.
             With Input_and_output(array 1, array 0), the statement is
             (Field.t array * Field.t array). *)
          let prev_statement =
            exists
              Typ.(public_input_typ 1 * public_input_typ 0)
              ~compute:(fun () -> ([| Field.Constant.zero |], [||]))
          in
          (* Witness the proof as an opaque prover value *)
          let prev_proof =
            exists (Typ.prover_value ()) ~compute:(fun () -> failwith "dummy")
          in
          let proof_must_verify = Boolean.true_ in
          let prev_input = fst prev_statement in
          Field.Assert.equal pub_field
            (Field.add prev_input.(0) (Field.of_int 1)) ;
          Promise.return
            { Pickles.Inductive_rule.previous_proof_statements =
                [ { public_input = prev_statement
                  ; proof = prev_proof
                  ; proof_must_verify
                  }
                ]
            ; public_output = [||]
            ; auxiliary_output = ()
            } )
    ; feature_flags = Pickles_types.Plonk_types.Features.none_bool
    }
end

let compile_recursive ~name =
  let tag, _cache, (module Proof), _provers =
    Pickles.compile_promise
      ~public_input:
        (Pickles.Inductive_rule.Input_and_output
           (public_input_typ 1, public_input_typ 0) )
      ~auxiliary_typ:Step.Typ.unit
      ~max_proofs_verified:(module Pickles_types.Nat.N1)
      ~name ~o1js_compatible_mode:false
      ~choices:(fun ~self ->
        [ Recursive.base_rule; Recursive.recursive_rule self ] )
      ()
  in
  let vk_promise =
    Pickles.Side_loaded.Verification_key.of_compiled_promise tag
  in
  let vk = Promise.block_on_async_exn (fun () -> vk_promise) in
  let hash = Mina_base.Zkapp_account.digest_vk vk in
  ignore
    ( Proof.verification_key_promise
      : Pickles.Verification_key.t Promise.t Lazy.t ) ;
  hash

(* ------------------------------------------------------------------ *)
(* Main: run all tests                                                 *)
(* ------------------------------------------------------------------ *)

let check_vk ~name ~expected ~actual =
  let hash_str = Kimchi_pasta.Pasta.Fp.to_string actual in
  printf "  VK hash (OCaml):  %s\n" hash_str ;
  printf "  VK hash (o1js):   %s\n" expected ;
  if String.equal hash_str expected then (printf "  PASS\n" ; true)
  else (
    printf "  FAIL - VK hashes differ\n" ;
    ignore name ;
    false )

let () =
  let expected_simple_vk_hash =
    "28164523456835703146609862384240602928554830215542611547995955594202748290944"
  in
  let expected_recursive_vk_hash =
    "3247524153122767581645069378962115724676436734987413176127638916743756576935"
  in
  let all_pass = ref true in

  printf "Pickles o1js compatibility test\n" ;
  printf "================================\n" ;

  (* --- Simple program (N0) --- *)
  printf "\n[simple-compat-test]\n" ;
  printf "  Compiling... %!" ;
  let simple_hash = compile_simple ~name:"simple-compat-test" in
  printf "done\n" ;
  if
    not
      (check_vk ~name:"simple" ~expected:expected_simple_vk_hash
         ~actual:simple_hash )
  then all_pass := false ;

  (* --- Recursive program (N1) --- *)
  ( match Stdlib.Sys.getenv_opt "SKIP_RECURSIVE" with
  | Some _ ->
      printf "\n[recursive-compat-test] SKIPPED (SKIP_RECURSIVE set)\n"
  | None ->
      printf "\n[recursive-compat-test]\n" ;
      printf "  Compiling... %!" ;
      let recursive_hash = compile_recursive ~name:"recursive-compat-test" in
      printf "done\n" ;
      if
        not
          (check_vk ~name:"recursive" ~expected:expected_recursive_vk_hash
             ~actual:recursive_hash )
      then all_pass := false ) ;

  if not !all_pass then (printf "\nFAILED\n" ; exit 1)
  else printf "\nAll compatibility checks passed.\n"
